---

- name: Install nginx/redis servers
  hosts: webapp
  # 'roles' instead of 'tasks'
  roles:
    - name: nginx-server
      tags:
        - nginx

- name: Install redis servers
  hosts: database
  # 'import_role' and 'include_role' are like the `roles` clause
  # but within a task list
  tasks:
    - name: Install redis servers
      ansible.builtin.import_role:
        name: redis-server
      vars:
        # passing non-default values
        port: 7379
      tags:
        - redis
