---
# show how facts acn be altered

- name: Showing set_fact use
  hosts: variables
  gather_facts: false
  vars:
      sum: 0
  pre_tasks:
    - name: Ensure that the variable does not exist
      ansible.builtin.assert:
        that:
          - my_blood_type is not defined
          - sum == 0
        quiet: true

  tasks:
    # set a new 'fact' (variable) as a string
    - name: Set my blood type and location
      ansible.builtin.set_fact:
        my_blood_type: "{{ location }}/{{ blood }}"

    - name: Show my_blood_type
      ansible.builtin.debug:
        var: my_blood_type

    # run through a loop, appending the new value to the end of the fact
    - name: Iterative accumulation
      ansible.builtin.set_fact:
        sum: "{{ sum }},{{ item * item }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5

    - name: Show sum
      ansible.builtin.debug:
        var: sum
