---
# multiple plays

- name: Lesson 1 - plays - install nginx
  hosts: all:!localhost
  tasks:
    - name: Install nginx
      become: true
      package:
        name: nginx

    - name: Start nginx
      become: true
      service:
        name: nginx
        state: started

- name: Lesson 1 - plays - localhost
  hosts: localhost
  tasks:
    - ansible.builtin.find:
        paths: "{{ ansible_env.PWD }}"
        patterns: "*.yml"
      register: local_yaml

    - name: Local yaml files found
      when: "'.yml' in item.path"
      debug:
        msg: "{{ item.path | basename }}"
      loop: "{{ local_yaml.files }}"
