---
# tasks file for nginx

- name: Load OS vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Update apt cache
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install nginx
  become: true
  package:
    state: present
    name: nginx
  notify: Start nginx

- name: Enable nginx
  become: true
  service:
    name: "{{ nginx_service_name }}"
    enabled: true
  notify: Start nginx
